controller:
  gains: [17.36, 24.30, 8.81, 2.54]

uav:
  J: [0.0820, 0.0845, 0.1377]
  m: 4.34
  d: 0.315
  ctf: 8.004e-4
  gravity: 9.81

# define the initial positions of each robot in NWU frame
robot_1:
  position: [1, 1, 0]
  velocity: [0, 0, 0]
#  rotation: [1, 0, 0, 0, -0.9995, -0.0314, 0, 0.0314, -0.9995]
  rotation: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  omega: [0, 0, 0]

robot_2:
  position: [-2, -2, 0]
  velocity: [0, 0, 0]
  rotation: [1, 0, 0, 0, 1, 0, 0, 0, 1]
#  rotation: [1, 0, 0, 0, -0.9995, -0.0314, 0, 0.0314, -0.9995]
  omega: [0, 0, 0]

robot_3:
  position: [-2, 2, 0]
  velocity: [0, 0, 0]
  rotation: [1, 0, 0, 0, 1, 0, 0, 0, 1]
#  rotation: [1, 0, 0, 0, -0.9995, -0.0314, 0, 0.0314, -0.9995]
  omega: [0, 0, 0]

robot_4:
  position: [2, -2, 0]
  velocity: [0, 0, 0]
  rotation: [1, 0, 0, 0, 1, 0, 0, 0, 1]
#  rotation: [1, 0, 0, 0, -0.9995, -0.0314, 0, 0.0314, -0.9995]
  omega: [0, 0, 0]